//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Infrastucture.Domain.Main.ServiceRest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BE_AsistenciaArchivo", Namespace="http://schemas.datacontract.org/2004/07/RestService")]
    [System.SerializableAttribute()]
    public partial class BE_AsistenciaArchivo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni {
            get {
                return this.DniField;
            }
            set {
                if ((object.ReferenceEquals(this.DniField, value) != true)) {
                    this.DniField = value;
                    this.RaisePropertyChanged("Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRest.IRestServiceImplementacion")]
    public interface IRestServiceImplementacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestServiceImplementacion/GetArchivo", ReplyAction="http://tempuri.org/IRestServiceImplementacion/GetArchivoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="BE_AsistenciaArchivo")]
        PetCenter.Infrastucture.Domain.Main.ServiceRest.BE_AsistenciaArchivo[] GetArchivo(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestServiceImplementacion/GetArchivo", ReplyAction="http://tempuri.org/IRestServiceImplementacion/GetArchivoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="BE_AsistenciaArchivo")]
        System.Threading.Tasks.Task<PetCenter.Infrastucture.Domain.Main.ServiceRest.BE_AsistenciaArchivo[]> GetArchivoAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestServiceImplementacion/ProcesarAsistencia", ReplyAction="http://tempuri.org/IRestServiceImplementacion/ProcesarAsistenciaResponse")]
        bool ProcesarAsistencia(string Mes, string Anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestServiceImplementacion/ProcesarAsistencia", ReplyAction="http://tempuri.org/IRestServiceImplementacion/ProcesarAsistenciaResponse")]
        System.Threading.Tasks.Task<bool> ProcesarAsistenciaAsync(string Mes, string Anio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestServiceImplementacionChannel : PetCenter.Infrastucture.Domain.Main.ServiceRest.IRestServiceImplementacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestServiceImplementacionClient : System.ServiceModel.ClientBase<PetCenter.Infrastucture.Domain.Main.ServiceRest.IRestServiceImplementacion>, PetCenter.Infrastucture.Domain.Main.ServiceRest.IRestServiceImplementacion {
        
        public RestServiceImplementacionClient() {
        }
        
        public RestServiceImplementacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestServiceImplementacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceImplementacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceImplementacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PetCenter.Infrastucture.Domain.Main.ServiceRest.BE_AsistenciaArchivo[] GetArchivo(string id) {
            return base.Channel.GetArchivo(id);
        }
        
        public System.Threading.Tasks.Task<PetCenter.Infrastucture.Domain.Main.ServiceRest.BE_AsistenciaArchivo[]> GetArchivoAsync(string id) {
            return base.Channel.GetArchivoAsync(id);
        }
        
        public bool ProcesarAsistencia(string Mes, string Anio) {
            return base.Channel.ProcesarAsistencia(Mes, Anio);
        }
        
        public System.Threading.Tasks.Task<bool> ProcesarAsistenciaAsync(string Mes, string Anio) {
            return base.Channel.ProcesarAsistenciaAsync(Mes, Anio);
        }
    }
}
