//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Common.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Concepto()
        {
            this.PlanillaEmpleadoConceptoes = new HashSet<PlanillaEmpleadoConcepto>();
        }
    
        public int ConceptoId { get; set; }
        public string Nombre { get; set; }
        public short Tipo { get; set; }
        public Nullable<short> TipoConcepto { get; set; }
        public string calculo1 { get; set; }
        public string calculo2 { get; set; }
        public string calculo3 { get; set; }
        public string calculo4 { get; set; }
        public string calculo5 { get; set; }
        public string calculo6 { get; set; }
        public string Operador1 { get; set; }
        public string Operador2 { get; set; }
        public string Operador3 { get; set; }
        public string Operador4 { get; set; }
        public string Operador5 { get; set; }
        public decimal Escala1 { get; set; }
        public decimal Escala2 { get; set; }
        public decimal Escala3 { get; set; }
        public decimal Escala4 { get; set; }
        public decimal Escala5 { get; set; }
        public decimal Escala6 { get; set; }
        public decimal Porcentaje1 { get; set; }
        public decimal Porcentaje2 { get; set; }
        public decimal Porcentaje3 { get; set; }
        public decimal Porcentaje4 { get; set; }
        public decimal Porcentaje5 { get; set; }
        public decimal Porcentaje6 { get; set; }
        public decimal Importe1 { get; set; }
        public decimal Importe2 { get; set; }
        public decimal Importe3 { get; set; }
        public decimal Importe4 { get; set; }
        public decimal Importe5 { get; set; }
        public decimal Importe6 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillaEmpleadoConcepto> PlanillaEmpleadoConceptoes { get; set; }
    }
}
