//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Common.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        public int ContratoId { get; set; }
        public int EmpleadoId { get; set; }
        public Nullable<bool> EsAfp { get; set; }
        public decimal SueldoBase { get; set; }
        public int UbigeoId { get; set; }
        public Nullable<decimal> JornadaTrabajo { get; set; }
        public string RenumeracionLetra { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public string Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
    }
}
