//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Common.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Falta
    {
        public int FaltaId { get; set; }
        public int EmpleadoId { get; set; }
        public Nullable<int> JustificacionId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public Nullable<System.DateTime> CantidadDias { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Justificacion Justificacion { get; set; }
    }
}
