//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Common.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanillaEmpleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanillaEmpleado()
        {
            this.PlanillaEmpleadoConceptoes = new HashSet<PlanillaEmpleadoConcepto>();
        }
    
        public int PlanillaEmpleadoId { get; set; }
        public int PlanillaId { get; set; }
        public int EmpleadoId { get; set; }
        public int AfpId { get; set; }
        public int OnpId { get; set; }
        public decimal TotalIngreso { get; set; }
        public decimal TotalDescuento { get; set; }
        public decimal TotalNeto { get; set; }
        public decimal TotalAporte { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Planilla Planilla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillaEmpleadoConcepto> PlanillaEmpleadoConceptoes { get; set; }
    }
}
