//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Common.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanillaEmpleadoConcepto
    {
        public int PlanillaEmpleadoConceptoId { get; set; }
        public int PlanillaEmpleadoId { get; set; }
        public int ConceptoId { get; set; }
        public decimal Importe { get; set; }
    
        public virtual Concepto Concepto { get; set; }
        public virtual PlanillaEmpleado PlanillaEmpleado { get; set; }
    }
}
