//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Common.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Planilla()
        {
            this.PlanillaEmpleadoes = new HashSet<PlanillaEmpleado>();
        }
    
        public int PlanillaId { get; set; }
        public Nullable<int> EmpleadoId_Aprueba { get; set; }
        public int UitId { get; set; }
        public int SueldoMinimoId { get; set; }
        public bool Aprobado { get; set; }
        public bool Pagado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual SueldoMinimo SueldoMinimo { get; set; }
        public virtual Uit Uit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanillaEmpleado> PlanillaEmpleadoes { get; set; }
    }
}
