//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Common.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguroVidaLey
    {
        public int SeguroVidaLeyId { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Valor { get; set; }
        public bool Estado { get; set; }
    }
}
